import type { Metadata } from "next";
import {
  Roboto_Mono,
  Libre_Baskerville,
  Abril_Fatface,
} from "next/font/google";
import "./globals.css";

const libreBaskerville = Libre_Baskerville({
  subsets: ["latin"],
  variable: "--font-libre-baskerville",
  weight: ["400", "700"],
  display: "swap",
});
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});
const abrilFatface = Abril_Fatface({
  subsets: ["latin"],
  variable: "--font-abril-fatface",
  weight: ["400"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Darius Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libreBaskerville.variable} ${robotoMono.className} ${abrilFatface.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
